/*
 * Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
 * 
 * On Sat Jan  4 15:35:11 GMT 2025
 * 
 */

/* Generation options: */
#ifndef __mkTop_h__
#define __mkTop_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkTop module */
class MOD_mkTop : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Wire<tUInt8> INST_abort;
  MOD_Fifo<tUWide> INST_f_reqs;
  MOD_Fifo<tUWide> INST_f_rsps;
  MOD_Reg<tUInt32> INST_lfsr_r;
  MOD_Reg<tUInt64> INST_mems_devices_rg_MTIME;
  MOD_Reg<tUInt32> INST_mems_devices_rg_logfile;
  MOD_Reg<tUInt8> INST_mems_devices_rg_running;
  MOD_CReg<tUWide> INST_mems_devices_spec_sto_buf_f_req_to_mem_rv;
  MOD_CReg<tUWide> INST_mems_devices_spec_sto_buf_f_rsp_from_mem_rv;
  MOD_Reg<tUInt64> INST_mems_devices_spec_sto_buf_rg_addr_base_mem;
  MOD_Reg<tUInt8> INST_mems_devices_spec_sto_buf_rg_free_ix;
  MOD_Reg<tUInt8> INST_mems_devices_spec_sto_buf_rg_fsm_state;
  MOD_Reg<tUInt32> INST_mems_devices_spec_sto_buf_rg_logfile;
  MOD_Reg<tUInt64> INST_mems_devices_spec_sto_buf_rg_size_B_mem;
  MOD_Reg<tUWide> INST_mems_devices_spec_sto_buf_vrg_sb_0;
  MOD_Reg<tUWide> INST_mems_devices_spec_sto_buf_vrg_sb_1;
  MOD_Reg<tUWide> INST_mems_devices_spec_sto_buf_vrg_sb_2;
  MOD_Reg<tUWide> INST_mems_devices_spec_sto_buf_vrg_sb_3;
  MOD_Reg<tUInt8> INST_running;
  MOD_Reg<tUInt8> INST_start_reg;
  MOD_Reg<tUInt8> INST_start_reg_1;
  MOD_Wire<tUInt8> INST_start_reg_2;
  MOD_Wire<tUInt8> INST_start_wire;
  MOD_Reg<tUInt8> INST_starting;
  MOD_Reg<tUInt8> INST_state_can_overlap;
  MOD_Reg<tUInt8> INST_state_fired;
  MOD_Wire<tUInt8> INST_state_fired_1;
  MOD_ConfigReg<tUInt8> INST_state_mkFSMstate;
  MOD_Wire<tUInt8> INST_state_overlap_pw;
  MOD_Wire<tUInt8> INST_state_set_pw;
 
 /* Constructor */
 public:
  MOD_mkTop(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_RL_action_l104c15;
  tUInt8 DEF_WILL_FIRE_RL_action_l103c16;
  tUInt8 DEF_WILL_FIRE_RL_action_l102c15;
  tUInt8 DEF_WILL_FIRE_RL_action_l101c16;
  tUInt8 DEF_WILL_FIRE_RL_action_l100c15;
  tUInt8 DEF_WILL_FIRE_RL_action_l99c16;
  tUInt8 DEF_WILL_FIRE_RL_action_l98c15;
  tUInt8 DEF_WILL_FIRE_RL_action_l97c16;
  tUInt8 DEF_WILL_FIRE_RL_action_l91c10;
  tUWide DEF_mems_devices_spec_sto_buf_f_rsp_from_mem_rv_po_ETC___d28;
  tUWide DEF_mems_devices_spec_sto_buf_f_rsp_from_mem_rv_po_ETC___d18;
  tUWide DEF_mems_devices_spec_sto_buf_f_req_to_mem_rv_port_ETC___d26;
 
 /* Local definitions */
 private:
  tUWide DEF_TASK_c_mems_devices_req_rsp___d164;
  tUWide DEF_TASK_c_mems_devices_req_rsp___d43;
  tUInt32 DEF_v__h7153;
  tUInt32 DEF_v__h4367;
  tUWide DEF_f_rsps_first____d318;
  tUWide DEF_f_reqs_first____d155;
  tUInt32 DEF_mems_devices_rg_logfile___d51;
  tUInt32 DEF_lfsr_value__h333;
  tUWide DEF_mems_devices_spec_sto_buf_f_req_to_mem_rv_port_ETC___d48;
  tUWide DEF_f_reqs_first__55_BITS_127_TO_0___d168;
  tUWide DEF_mems_devices_spec_sto_buf_f_req_to_mem_rv_port_ETC___d47;
  tUWide DEF_f_reqs_first__55_BITS_262_TO_192___d167;
  tUInt64 DEF_f_rsps_first__18_BITS_262_TO_199___d386;
  tUInt64 DEF_f_rsps_first__18_BITS_191_TO_128___d376;
  tUInt64 DEF_f_rsps_first__18_BITS_127_TO_64___d319;
  tUInt32 DEF_f_rsps_first__18_BITS_63_TO_32___d320;
  tUInt32 DEF_f_rsps_first__18_BITS_31_TO_0___d321;
  tUInt8 DEF_mrt__h23588;
  tUInt8 DEF_f_rsps_first__18_BITS_264_TO_263___d377;
  tUInt8 DEF_f_rsps_first__18_BITS_193_TO_192___d367;
  tUInt8 DEF_f_rsps_first__18_BITS_198_TO_194_22_EQ_0b11111___d324;
  tUInt8 DEF_f_rsps_first__18_BITS_198_TO_194_22_EQ_0b11110___d323;
  tUInt8 DEF_f_rsps_first__18_BITS_198_TO_194_22_EQ_0b11101___d325;
  tUInt8 DEF_f_rsps_first__18_BITS_198_TO_194_22_EQ_0b11100___d337;
  tUInt8 DEF_f_rsps_first__18_BITS_198_TO_194_22_EQ_0b11001___d326;
  tUInt8 DEF_f_rsps_first__18_BITS_198_TO_194_22_EQ_0b11000___d336;
  tUInt8 DEF_f_rsps_first__18_BITS_198_TO_194_22_EQ_0b10100___d335;
  tUInt8 DEF_f_rsps_first__18_BITS_198_TO_194_22_EQ_0b10000___d334;
  tUInt8 DEF_f_rsps_first__18_BITS_198_TO_194_22_EQ_0b1100___d332;
  tUInt8 DEF_f_rsps_first__18_BITS_198_TO_194_22_EQ_0b1000___d333;
  tUInt8 DEF_f_rsps_first__18_BITS_198_TO_194_22_EQ_0b100___d331;
  tUInt8 DEF_f_rsps_first__18_BITS_198_TO_194_22_EQ_0b11___d328;
  tUInt8 DEF_f_rsps_first__18_BITS_198_TO_194_22_EQ_0b10___d327;
  tUInt8 DEF_f_rsps_first__18_BITS_198_TO_194_22_EQ_0b1___d329;
  tUInt8 DEF_f_rsps_first__18_BITS_198_TO_194_22_EQ_0b0___d330;
  tUInt8 DEF_f_rsps_first__18_BITS_264_TO_263_77_EQ_2___d380;
  tUInt8 DEF_f_rsps_first__18_BITS_264_TO_263_77_EQ_1___d379;
  tUInt8 DEF_f_rsps_first__18_BITS_264_TO_263_77_EQ_0___d378;
  tUInt8 DEF_f_rsps_first__18_BITS_193_TO_192_67_EQ_2___d370;
  tUInt8 DEF_f_rsps_first__18_BITS_193_TO_192_67_EQ_1___d369;
  tUInt8 DEF_f_rsps_first__18_BITS_193_TO_192_67_EQ_0___d368;
  tUInt8 DEF_NOT_f_rsps_first__18_BITS_264_TO_263_77_EQ_0_7_ETC___d385;
  tUInt8 DEF_NOT_f_rsps_first__18_BITS_193_TO_192_67_EQ_0_6_ETC___d375;
  tUInt8 DEF_NOT_f_rsps_first__18_BITS_198_TO_194_22_EQ_0b1_ETC___d366;
  tUInt8 DEF_NOT_mems_devices_rg_logfile_1_EQ_0_2___d53;
  tUWide DEF__1_CONCAT_TASK_c_mems_devices_req_rsp_3_BITS_1__ETC___d50;
  tUWide DEF_TASK_c_mems_devices_req_rsp_3_BITS_1_TO_0_4_CO_ETC___d46;
  tUWide DEF_mems_devices_spec_sto_buf_f_req_to_mem_rv_port_ETC___d49;
  tUWide DEF__0_CONCAT_DONTCARE___d23;
  tUWide DEF_TASK_c_mems_devices_req_rsp_64_BITS_1_TO_0_65__ETC___d169;
  tUWide DEF__0_CONCAT_DONTCARE___d34;
  tUWide DEF__122_CONCAT_32768_CONCAT_lfsr_r_09_CONCAT_DONTC_ETC___d313;
  tUInt64 DEF_x1_avValue_mem_req_addr__h23140;
  tUWide DEF_DONTCARE_CONCAT_1_CONCAT_0x8000_CONCAT_lfsr_r__ETC___d312;
  tUWide DEF_wdata__h4052;
  tUWide DEF_wdata__h6969;
  tUInt32 DEF_pc__h23100;
 
 /* Rules */
 public:
  void RL_start();
  void RL_run();
  void RL_mems_devices_spec_sto_buf_rl_mem_wr_rsp();
  void RL_mems_devices_rl_count_MTIME();
  void RL_mems_devices_rl_DMem_req_rsp();
  void RL_mems_devices_rl_Dbg_req_rsp();
  void RL_start_reg__dreg_update();
  void RL_state_handle_abort();
  void RL_state_fired__dreg_update();
  void RL_state_every();
  void RL_restart();
  void RL_action_l91c10();
  void RL_action_l97c16();
  void RL_action_l98c15();
  void RL_action_l99c16();
  void RL_action_l100c15();
  void RL_action_l101c16();
  void RL_action_l102c15();
  void RL_action_l103c16();
  void RL_action_l104c15();
  void RL_idle_l90c7();
  void RL_fsm_start();
  void RL_auto_start();
  void RL_auto_finish();
  void __me_check_11();
  void __me_check_12();
  void __me_check_13();
  void __me_check_14();
  void __me_check_15();
  void __me_check_16();
  void __me_check_17();
  void __me_check_18();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTop &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTop &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTop &backing);
};

#endif /* ifndef __mkTop_h__ */
