/*
 * Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
 * 
 * On Sat Jan  4 15:35:11 GMT 2025
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkTop.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkTop::MODEL_mkTop()
{
  mkTop_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkTop()
{
  MODEL_mkTop *model = new MODEL_mkTop();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkTop &INST_top = *((MOD_mkTop *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_abort_whas__70_AND_abort_wget__71_72_OR_state__ETC___d409;
	 tUInt8 DEF_INST_top_DEF_abort_whas__70_AND_abort_wget__71_72_OR_state__ETC___d413;
	 tUInt8 DEF_INST_top_DEF_NOT_start_wire_whas__73_74_OR_NOT_start_wire_w_ETC___d277;
	 tUInt8 DEF_INST_top_DEF_abort_whas__70_AND_abort_wget__71___d272;
	 tUInt8 DEF_INST_top_DEF_NOT_abort_whas__70_92_OR_NOT_abort_wget__71_93___d294;
	 tUInt8 DEF_INST_top_DEF_abort_whas__70_AND_abort_wget__71_72_OR_state__ETC___d302;
	 tUInt8 DEF_INST_top_DEF_state_mkFSMstate_read__98_EQ_9___d301;
	 tUInt8 DEF_INST_top_DEF_x__h3062;
	 tUInt8 DEF_INST_top_DEF_f_reqs_i_notFull____d305;
	 tUInt8 DEF_INST_top_DEF_f_rsps_i_notEmpty____d314;
	 tUInt8 DEF_INST_top_DEF_abort_wget____d271;
	 tUInt8 DEF_INST_top_DEF_abort_whas____d270;
	 tUInt8 DEF_INST_top_DEF_start_reg__h26438;
	 tUInt8 DEF_INST_top_DEF_running__h26524;
	 tUInt8 DEF_INST_top_DEF_start_wire_wget____d275;
	 tUInt8 DEF_INST_top_DEF_start_wire_whas____d273;
	 tUInt8 DEF_INST_top_DEF_mems_devices_rg_running___d32;
	 tUInt8 DEF_INST_top_DEF_start_reg_1__h22164;
	 tUInt8 DEF_INST_top_DEF_state_fired__h22166;
	 tUInt8 DEF_INST_top_DEF_state_mkFSMstate_read____d298;
	 tUInt8 DEF_INST_top_DEF_starting__h296;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_start;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_start;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_run;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_run;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_mems_devices_spec_sto_buf_rl_mem_wr_rsp;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_mems_devices_spec_sto_buf_rl_mem_wr_rsp;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_mems_devices_rl_count_MTIME;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_mems_devices_rl_count_MTIME;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_mems_devices_rl_DMem_req_rsp;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_mems_devices_rl_DMem_req_rsp;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_mems_devices_rl_Dbg_req_rsp;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_mems_devices_rl_Dbg_req_rsp;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_start_reg__dreg_update;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_start_reg__dreg_update;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_state_handle_abort;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_state_handle_abort;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_state_fired__dreg_update;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_state_fired__dreg_update;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_state_every;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_state_every;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_restart;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_restart;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l91c10;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l97c16;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l98c15;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l99c16;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l100c15;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l101c16;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l102c15;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l103c16;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l104c15;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_idle_l90c7;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_idle_l90c7;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_fsm_start;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_fsm_start;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_auto_start;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_auto_start;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_auto_finish;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_auto_finish;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_11;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_12;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_12;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_13;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_13;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_14;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_14;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_15;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_15;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_16;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_16;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_17;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_17;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_18;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_18;
	 DEF_INST_top_DEF_state_mkFSMstate_read____d298 = INST_top.INST_state_mkFSMstate.METH_read();
	 DEF_INST_top_DEF_abort_whas____d270 = INST_top.INST_abort.METH_whas();
	 DEF_INST_top_DEF_abort_wget____d271 = INST_top.INST_abort.METH_wget();
	 DEF_INST_top_DEF_f_rsps_i_notEmpty____d314 = INST_top.INST_f_rsps.METH_i_notEmpty();
	 DEF_INST_top_DEF_NOT_abort_whas__70_92_OR_NOT_abort_wget__71_93___d294 = !DEF_INST_top_DEF_abort_whas____d270 || !DEF_INST_top_DEF_abort_wget____d271;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l100c15 = DEF_INST_top_DEF_f_rsps_i_notEmpty____d314 && (DEF_INST_top_DEF_NOT_abort_whas__70_92_OR_NOT_abort_wget__71_93___d294 && DEF_INST_top_DEF_state_mkFSMstate_read____d298 == (tUInt8)4u);
	 INST_top.DEF_WILL_FIRE_RL_action_l100c15 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l100c15;
	 DEF_INST_top_DEF_f_reqs_i_notFull____d305 = INST_top.INST_f_reqs.METH_i_notFull();
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l101c16 = DEF_INST_top_DEF_f_reqs_i_notFull____d305 && (DEF_INST_top_DEF_NOT_abort_whas__70_92_OR_NOT_abort_wget__71_93___d294 && DEF_INST_top_DEF_state_mkFSMstate_read____d298 == (tUInt8)5u);
	 INST_top.DEF_WILL_FIRE_RL_action_l101c16 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l101c16;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l102c15 = DEF_INST_top_DEF_f_rsps_i_notEmpty____d314 && (DEF_INST_top_DEF_NOT_abort_whas__70_92_OR_NOT_abort_wget__71_93___d294 && DEF_INST_top_DEF_state_mkFSMstate_read____d298 == (tUInt8)6u);
	 INST_top.DEF_WILL_FIRE_RL_action_l102c15 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l102c15;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l103c16 = DEF_INST_top_DEF_f_reqs_i_notFull____d305 && (DEF_INST_top_DEF_NOT_abort_whas__70_92_OR_NOT_abort_wget__71_93___d294 && DEF_INST_top_DEF_state_mkFSMstate_read____d298 == (tUInt8)7u);
	 INST_top.DEF_WILL_FIRE_RL_action_l103c16 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l103c16;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l104c15 = DEF_INST_top_DEF_f_rsps_i_notEmpty____d314 && (DEF_INST_top_DEF_NOT_abort_whas__70_92_OR_NOT_abort_wget__71_93___d294 && DEF_INST_top_DEF_state_mkFSMstate_read____d298 == (tUInt8)8u);
	 INST_top.DEF_WILL_FIRE_RL_action_l104c15 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l104c15;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l97c16 = DEF_INST_top_DEF_f_reqs_i_notFull____d305 && (DEF_INST_top_DEF_NOT_abort_whas__70_92_OR_NOT_abort_wget__71_93___d294 && DEF_INST_top_DEF_state_mkFSMstate_read____d298 == (tUInt8)1u);
	 INST_top.DEF_WILL_FIRE_RL_action_l97c16 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l97c16;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l98c15 = DEF_INST_top_DEF_f_rsps_i_notEmpty____d314 && (DEF_INST_top_DEF_NOT_abort_whas__70_92_OR_NOT_abort_wget__71_93___d294 && DEF_INST_top_DEF_state_mkFSMstate_read____d298 == (tUInt8)2u);
	 INST_top.DEF_WILL_FIRE_RL_action_l98c15 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l98c15;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l99c16 = DEF_INST_top_DEF_f_reqs_i_notFull____d305 && (DEF_INST_top_DEF_NOT_abort_whas__70_92_OR_NOT_abort_wget__71_93___d294 && DEF_INST_top_DEF_state_mkFSMstate_read____d298 == (tUInt8)3u);
	 INST_top.DEF_WILL_FIRE_RL_action_l99c16 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l99c16;
	 DEF_INST_top_DEF_state_fired__h22166 = INST_top.INST_state_fired.METH_read();
	 DEF_INST_top_DEF_start_reg_1__h22164 = INST_top.INST_start_reg_1.METH_read();
	 DEF_INST_top_DEF_running__h26524 = INST_top.INST_running.METH_read();
	 DEF_INST_top_DEF_start_reg__h26438 = INST_top.INST_start_reg.METH_read();
	 DEF_INST_top_DEF_state_mkFSMstate_read__98_EQ_9___d301 = DEF_INST_top_DEF_state_mkFSMstate_read____d298 == (tUInt8)9u;
	 DEF_INST_top_DEF_abort_whas__70_AND_abort_wget__71___d272 = DEF_INST_top_DEF_abort_whas____d270 && DEF_INST_top_DEF_abort_wget____d271;
	 DEF_INST_top_DEF_abort_whas__70_AND_abort_wget__71_72_OR_state__ETC___d302 = (DEF_INST_top_DEF_abort_whas__70_AND_abort_wget__71___d272 || DEF_INST_top_DEF_state_mkFSMstate_read____d298 == (tUInt8)0u) || DEF_INST_top_DEF_state_mkFSMstate_read__98_EQ_9___d301;
	 DEF_INST_top_DEF_abort_whas__70_AND_abort_wget__71_72_OR_state__ETC___d409 = DEF_INST_top_DEF_abort_whas__70_AND_abort_wget__71_72_OR_state__ETC___d302 && (!DEF_INST_top_DEF_start_reg_1__h22164 || DEF_INST_top_DEF_state_fired__h22166);
	 DEF_INST_top_DEF_abort_whas__70_AND_abort_wget__71_72_OR_state__ETC___d413 = DEF_INST_top_DEF_abort_whas__70_AND_abort_wget__71_72_OR_state__ETC___d409 && !DEF_INST_top_DEF_start_reg__h26438;
	 DEF_INST_top_DEF_CAN_FIRE_RL_auto_finish = DEF_INST_top_DEF_running__h26524 && DEF_INST_top_DEF_abort_whas__70_AND_abort_wget__71_72_OR_state__ETC___d413;
	 DEF_INST_top_DEF_WILL_FIRE_RL_auto_finish = DEF_INST_top_DEF_CAN_FIRE_RL_auto_finish;
	 DEF_INST_top_DEF_CAN_FIRE_RL_auto_start = DEF_INST_top_DEF_abort_whas__70_AND_abort_wget__71_72_OR_state__ETC___d413 && !DEF_INST_top_DEF_running__h26524;
	 DEF_INST_top_DEF_WILL_FIRE_RL_auto_start = DEF_INST_top_DEF_CAN_FIRE_RL_auto_start;
	 DEF_INST_top_DEF_CAN_FIRE_RL_fsm_start = DEF_INST_top_DEF_abort_whas__70_AND_abort_wget__71_72_OR_state__ETC___d409 && DEF_INST_top_DEF_start_reg__h26438;
	 DEF_INST_top_DEF_WILL_FIRE_RL_fsm_start = DEF_INST_top_DEF_CAN_FIRE_RL_fsm_start;
	 DEF_INST_top_DEF_mems_devices_rg_running___d32 = INST_top.INST_mems_devices_rg_running.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_mems_devices_rl_Dbg_req_rsp = (INST_top.INST_f_reqs.METH_i_notEmpty() && INST_top.INST_f_rsps.METH_i_notFull()) && DEF_INST_top_DEF_mems_devices_rg_running___d32;
	 DEF_INST_top_DEF_WILL_FIRE_RL_mems_devices_rl_Dbg_req_rsp = DEF_INST_top_DEF_CAN_FIRE_RL_mems_devices_rl_Dbg_req_rsp;
	 DEF_INST_top_DEF_CAN_FIRE_RL_mems_devices_rl_count_MTIME = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_mems_devices_rl_count_MTIME = DEF_INST_top_DEF_CAN_FIRE_RL_mems_devices_rl_count_MTIME;
	 INST_top.DEF_mems_devices_spec_sto_buf_f_rsp_from_mem_rv_po_ETC___d18 = INST_top.INST_mems_devices_spec_sto_buf_f_rsp_from_mem_rv.METH_port0__read();
	 DEF_INST_top_DEF_x__h3062 = INST_top.DEF_mems_devices_spec_sto_buf_f_rsp_from_mem_rv_po_ETC___d18.get_bits_in_word8(6u,
															     2u,
															     5u);
	 DEF_INST_top_DEF_CAN_FIRE_RL_mems_devices_spec_sto_buf_rl_mem_wr_rsp = INST_top.DEF_mems_devices_spec_sto_buf_f_rsp_from_mem_rv_po_ETC___d18.get_bits_in_word8(8u,
																					9u,
																					1u) && DEF_INST_top_DEF_x__h3062 == (tUInt8)31u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_mems_devices_spec_sto_buf_rl_mem_wr_rsp = DEF_INST_top_DEF_CAN_FIRE_RL_mems_devices_spec_sto_buf_rl_mem_wr_rsp;
	 DEF_INST_top_DEF_CAN_FIRE_RL_restart = (DEF_INST_top_DEF_start_reg_1__h22164 && !DEF_INST_top_DEF_state_fired__h22166) && DEF_INST_top_DEF_NOT_abort_whas__70_92_OR_NOT_abort_wget__71_93___d294;
	 DEF_INST_top_DEF_WILL_FIRE_RL_restart = DEF_INST_top_DEF_CAN_FIRE_RL_restart;
	 DEF_INST_top_DEF_starting__h296 = INST_top.INST_starting.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_run = !DEF_INST_top_DEF_starting__h296;
	 DEF_INST_top_DEF_WILL_FIRE_RL_run = DEF_INST_top_DEF_CAN_FIRE_RL_run;
	 DEF_INST_top_DEF_CAN_FIRE_RL_start = DEF_INST_top_DEF_starting__h296;
	 DEF_INST_top_DEF_WILL_FIRE_RL_start = DEF_INST_top_DEF_CAN_FIRE_RL_start;
	 DEF_INST_top_DEF_CAN_FIRE_RL_start_reg__dreg_update = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_start_reg__dreg_update = DEF_INST_top_DEF_CAN_FIRE_RL_start_reg__dreg_update;
	 DEF_INST_top_DEF_CAN_FIRE_RL_state_every = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_state_every = DEF_INST_top_DEF_CAN_FIRE_RL_state_every;
	 DEF_INST_top_DEF_CAN_FIRE_RL_state_fired__dreg_update = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_state_fired__dreg_update = DEF_INST_top_DEF_CAN_FIRE_RL_state_fired__dreg_update;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_11 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_11 = DEF_INST_top_DEF_CAN_FIRE___me_check_11;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_12 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_12 = DEF_INST_top_DEF_CAN_FIRE___me_check_12;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_15 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_15 = DEF_INST_top_DEF_CAN_FIRE___me_check_15;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_13 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_13 = DEF_INST_top_DEF_CAN_FIRE___me_check_13;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_14 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_14 = DEF_INST_top_DEF_CAN_FIRE___me_check_14;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_16 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_16 = DEF_INST_top_DEF_CAN_FIRE___me_check_16;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_17 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_17 = DEF_INST_top_DEF_CAN_FIRE___me_check_17;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_18 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_18 = DEF_INST_top_DEF_CAN_FIRE___me_check_18;
	 if (INST_top.DEF_WILL_FIRE_RL_action_l100c15)
	   INST_top.RL_action_l100c15();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l101c16)
	   INST_top.RL_action_l101c16();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l104c15)
	   INST_top.RL_action_l104c15();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l102c15)
	   INST_top.RL_action_l102c15();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l103c16)
	   INST_top.RL_action_l103c16();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l97c16)
	   INST_top.RL_action_l97c16();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l98c15)
	   INST_top.RL_action_l98c15();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l99c16)
	   INST_top.RL_action_l99c16();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_auto_start)
	   INST_top.RL_auto_start();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_mems_devices_rl_count_MTIME)
	   INST_top.RL_mems_devices_rl_count_MTIME();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_restart)
	   INST_top.RL_restart();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_mems_devices_spec_sto_buf_rl_mem_wr_rsp)
	   INST_top.RL_mems_devices_spec_sto_buf_rl_mem_wr_rsp();
	 INST_top.DEF_mems_devices_spec_sto_buf_f_rsp_from_mem_rv_po_ETC___d28 = INST_top.INST_mems_devices_spec_sto_buf_f_rsp_from_mem_rv.METH_port1__read();
	 INST_top.DEF_mems_devices_spec_sto_buf_f_req_to_mem_rv_port_ETC___d26 = INST_top.INST_mems_devices_spec_sto_buf_f_req_to_mem_rv.METH_port1__read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_mems_devices_rl_DMem_req_rsp = (INST_top.DEF_mems_devices_spec_sto_buf_f_req_to_mem_rv_port_ETC___d26.get_bits_in_word8(8u,
																			      7u,
																			      1u) && !INST_top.DEF_mems_devices_spec_sto_buf_f_rsp_from_mem_rv_po_ETC___d28.get_bits_in_word8(8u,
																															      9u,
																															      1u)) && DEF_INST_top_DEF_mems_devices_rg_running___d32;
	 DEF_INST_top_DEF_WILL_FIRE_RL_mems_devices_rl_DMem_req_rsp = DEF_INST_top_DEF_CAN_FIRE_RL_mems_devices_rl_DMem_req_rsp;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_run)
	   INST_top.RL_run();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_start)
	   INST_top.RL_start();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_12)
	   INST_top.__me_check_12();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_13)
	   INST_top.__me_check_13();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_14)
	   INST_top.__me_check_14();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_15)
	   INST_top.__me_check_15();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_16)
	   INST_top.__me_check_16();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_17)
	   INST_top.__me_check_17();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_18)
	   INST_top.__me_check_18();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_fsm_start)
	   INST_top.RL_fsm_start();
	 DEF_INST_top_DEF_start_wire_whas____d273 = INST_top.INST_start_wire.METH_whas();
	 DEF_INST_top_DEF_start_wire_wget____d275 = INST_top.INST_start_wire.METH_wget();
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l91c10 = (!DEF_INST_top_DEF_mems_devices_rg_running___d32 && ((DEF_INST_top_DEF_start_wire_whas____d273 && DEF_INST_top_DEF_start_wire_wget____d275) && DEF_INST_top_DEF_abort_whas__70_AND_abort_wget__71_72_OR_state__ETC___d302)) && !(((DEF_INST_top_DEF_CAN_FIRE_RL_action_l104c15 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l103c16) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l102c15 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l101c16)) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_l100c15 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l99c16) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l98c15 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l97c16)));
	 INST_top.DEF_WILL_FIRE_RL_action_l91c10 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l91c10;
	 DEF_INST_top_DEF_NOT_start_wire_whas__73_74_OR_NOT_start_wire_w_ETC___d277 = !DEF_INST_top_DEF_start_wire_whas____d273 || !DEF_INST_top_DEF_start_wire_wget____d275;
	 DEF_INST_top_DEF_CAN_FIRE_RL_idle_l90c7 = (DEF_INST_top_DEF_NOT_start_wire_whas__73_74_OR_NOT_start_wire_w_ETC___d277 && (DEF_INST_top_DEF_NOT_abort_whas__70_92_OR_NOT_abort_wget__71_93___d294 && DEF_INST_top_DEF_state_mkFSMstate_read__98_EQ_9___d301)) && !(((DEF_INST_top_DEF_CAN_FIRE_RL_action_l104c15 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l103c16) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l102c15 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l101c16)) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_l100c15 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l99c16) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l98c15 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l97c16)));
	 DEF_INST_top_DEF_WILL_FIRE_RL_idle_l90c7 = DEF_INST_top_DEF_CAN_FIRE_RL_idle_l90c7;
	 DEF_INST_top_DEF_CAN_FIRE_RL_state_handle_abort = (DEF_INST_top_DEF_abort_whas__70_AND_abort_wget__71___d272 && DEF_INST_top_DEF_NOT_start_wire_whas__73_74_OR_NOT_start_wire_w_ETC___d277) && !((((DEF_INST_top_DEF_CAN_FIRE_RL_action_l104c15 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l103c16) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l102c15 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l101c16)) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_l100c15 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l99c16) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l98c15 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l97c16))) || DEF_INST_top_DEF_CAN_FIRE_RL_restart);
	 DEF_INST_top_DEF_WILL_FIRE_RL_state_handle_abort = DEF_INST_top_DEF_CAN_FIRE_RL_state_handle_abort;
	 if (INST_top.DEF_WILL_FIRE_RL_action_l91c10)
	   INST_top.RL_action_l91c10();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_auto_finish)
	   INST_top.RL_auto_finish();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_mems_devices_rl_Dbg_req_rsp)
	   INST_top.RL_mems_devices_rl_Dbg_req_rsp();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_mems_devices_rl_DMem_req_rsp)
	   INST_top.RL_mems_devices_rl_DMem_req_rsp();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_start_reg__dreg_update)
	   INST_top.RL_start_reg__dreg_update();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_state_handle_abort)
	   INST_top.RL_state_handle_abort();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_11)
	   INST_top.__me_check_11();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_idle_l90c7)
	   INST_top.RL_idle_l90c7();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_state_every)
	   INST_top.RL_state_every();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_state_fired__dreg_update)
	   INST_top.RL_state_fired__dreg_update();
	 INST_top.INST_state_fired_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_state_overlap_pw.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_state_set_pw.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_abort.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_start_reg_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_start_wire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_mems_devices_spec_sto_buf_f_rsp_from_mem_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_mems_devices_spec_sto_buf_f_req_to_mem_rv.clk((tUInt8)1u, (tUInt8)1u);
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_f_reqs.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_f_rsps.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_lfsr_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_starting.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mems_devices_spec_sto_buf_rg_logfile.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mems_devices_spec_sto_buf_f_req_to_mem_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_mems_devices_spec_sto_buf_f_rsp_from_mem_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_mems_devices_spec_sto_buf_rg_free_ix.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mems_devices_spec_sto_buf_rg_fsm_state.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mems_devices_rg_running.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mems_devices_rg_logfile.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mems_devices_rg_MTIME.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_start_reg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_start_reg_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_state_mkFSMstate.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_state_fired.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_state_can_overlap.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_running.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkTop::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkTop_instance = new MOD_mkTop(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkTop_instance->INST_f_reqs.set_clk_0)("CLK");
  (mkTop_instance->INST_f_rsps.set_clk_0)("CLK");
  (mkTop_instance->INST_mems_devices_spec_sto_buf_f_req_to_mem_rv.set_clk_0)("CLK");
  (mkTop_instance->INST_mems_devices_spec_sto_buf_f_rsp_from_mem_rv.set_clk_0)("CLK");
  (mkTop_instance->INST_start_wire.set_clk_0)("CLK");
  (mkTop_instance->INST_start_reg_2.set_clk_0)("CLK");
  (mkTop_instance->INST_abort.set_clk_0)("CLK");
  (mkTop_instance->INST_state_set_pw.set_clk_0)("CLK");
  (mkTop_instance->INST_state_overlap_pw.set_clk_0)("CLK");
  (mkTop_instance->INST_state_fired_1.set_clk_0)("CLK");
  (mkTop_instance->set_clk_0)("CLK");
}
void MODEL_mkTop::destroy_model()
{
  delete mkTop_instance;
  mkTop_instance = NULL;
}
void MODEL_mkTop::reset_model(bool asserted)
{
  (mkTop_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkTop::get_instance()
{
  return mkTop_instance;
}

/* Fill in version numbers */
void MODEL_mkTop::get_version(char const **name, char const **build)
{
  *name = "2024.07";
  *build = "b4f31db";
}

/* Get the model creation time */
time_t MODEL_mkTop::get_creation_time()
{
  
  /* Sat Jan  4 15:35:11 UTC 2025 */
  return 1736004911llu;
}

/* State dumping function */
void MODEL_mkTop::dump_state()
{
  (mkTop_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkTop & mkTop_backing(tSimStateHdl simHdl)
{
  static MOD_mkTop *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkTop(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkTop::dump_VCD_defs()
{
  (mkTop_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkTop::dump_VCD(tVCDDumpType dt)
{
  (mkTop_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkTop_backing(sim_hdl));
}
