/*
 * Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
 * 
 * On Tue Dec 31 19:53:04 GMT 2024
 * 
 */

/* Generation options: */
#ifndef __mkTop_h__
#define __mkTop_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkTop module */
class MOD_mkTop : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Wire<tUInt8> INST_abort;
  MOD_Reg<tUInt8> INST_fired;
  MOD_Wire<tUInt8> INST_fired_1;
  MOD_Reg<tUInt8> INST_running;
  MOD_Reg<tUInt8> INST_start_reg;
  MOD_Reg<tUInt8> INST_start_reg_1;
  MOD_Wire<tUInt8> INST_start_reg_2;
  MOD_Wire<tUInt8> INST_start_wire;
 
 /* Constructor */
 public:
  MOD_mkTop(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
  tUWide DEF__41514448764394106623788834275472493772800_CONC_ETC___d20;
 
 /* Rules */
 public:
  void RL_start_reg__dreg_update();
  void RL_fired__dreg_update();
  void RL_restart();
  void RL_action_l22c10();
  void RL_fsm_start();
  void RL_auto_start();
  void RL_auto_finish();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTop &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTop &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTop &backing);
};

#endif /* ifndef __mkTop_h__ */
