/*
 * Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
 * 
 * On Fri Jan  3 21:31:10 GMT 2025
 * 
 */
extern "C" {
  void c_mems_devices_init(unsigned int );
  void c_mems_devices_req_rsp(unsigned int *,
			      unsigned long long ,
			      unsigned int ,
			      unsigned int ,
			      unsigned long long ,
			      unsigned int ,
			      unsigned int *);
}
