/*
 * Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
 * 
 * On Fri Jan  3 21:31:10 GMT 2025
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkTop.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkTop::MODEL_mkTop()
{
  mkTop_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkTop()
{
  MODEL_mkTop *model = new MODEL_mkTop();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkTop &INST_top = *((MOD_mkTop *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_abort_whas__53_AND_abort_wget__54_55_OR_state__ETC___d458;
	 tUInt8 DEF_INST_top_DEF_abort_whas__53_AND_abort_wget__54_55_OR_state__ETC___d462;
	 tUInt8 DEF_INST_top_DEF_NOT_start_wire_whas__56_57_OR_NOT_start_wire_w_ETC___d260;
	 tUInt8 DEF_INST_top_DEF_abort_whas__53_AND_abort_wget__54___d255;
	 tUInt8 DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277;
	 tUInt8 DEF_INST_top_DEF_abort_whas__53_AND_abort_wget__54_55_OR_state__ETC___d285;
	 tUInt8 DEF_INST_top_DEF_state_mkFSMstate_read__81_EQ_29___d284;
	 tUInt8 DEF_INST_top_DEF_x__h2881;
	 tUInt8 DEF_INST_top_DEF_f_reqs_i_notFull____d288;
	 tUInt8 DEF_INST_top_DEF_f_rsps_i_notEmpty____d304;
	 tUInt8 DEF_INST_top_DEF_abort_wget____d254;
	 tUInt8 DEF_INST_top_DEF_abort_whas____d253;
	 tUInt8 DEF_INST_top_DEF_start_reg__h61647;
	 tUInt8 DEF_INST_top_DEF_running__h61733;
	 tUInt8 DEF_INST_top_DEF_start_wire_wget____d258;
	 tUInt8 DEF_INST_top_DEF_start_wire_whas____d256;
	 tUInt8 DEF_INST_top_DEF_mems_devices_rg_running___d15;
	 tUInt8 DEF_INST_top_DEF_start_reg_1__h50556;
	 tUInt8 DEF_INST_top_DEF_state_fired__h50558;
	 tUInt8 DEF_INST_top_DEF_state_mkFSMstate_read____d281;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_mems_devices_spec_sto_buf_rl_mem_wr_rsp;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_mems_devices_spec_sto_buf_rl_mem_wr_rsp;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_mems_devices_rl_count_MTIME;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_mems_devices_rl_count_MTIME;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_mems_devices_rl_DMem_req_rsp;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_mems_devices_rl_DMem_req_rsp;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_mems_devices_rl_Dbg_req_rsp;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_mems_devices_rl_Dbg_req_rsp;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_start_reg__dreg_update;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_start_reg__dreg_update;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_state_handle_abort;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_state_handle_abort;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_state_fired__dreg_update;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_state_fired__dreg_update;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_state_every;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_state_every;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_restart;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_restart;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l82c10;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l88c11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l89c11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l90c11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l91c11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l92c11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l93c11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l94c11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l95c11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l96c11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l97c11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l98c11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l99c11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l100c11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l101c11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l102c11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l103c11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l104c11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l105c11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l106c11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l107c11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l108c11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l109c11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l110c11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l111c11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l112c11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l113c11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l114c11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l115c11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_idle_l81c7;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_idle_l81c7;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_fsm_start;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_fsm_start;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_auto_start;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_auto_start;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_auto_finish;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_auto_finish;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_9;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_9;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_10;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_10;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_11;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_12;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_12;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_13;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_13;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_14;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_14;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_15;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_15;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_16;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_16;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_17;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_17;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_18;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_18;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_19;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_19;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_20;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_20;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_21;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_21;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_22;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_22;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_23;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_23;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_24;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_24;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_25;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_25;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_26;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_26;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_27;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_27;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_28;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_28;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_29;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_29;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_30;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_30;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_31;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_31;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_32;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_32;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_33;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_33;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_34;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_34;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_35;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_35;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_36;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_36;
	 DEF_INST_top_DEF_state_mkFSMstate_read____d281 = INST_top.INST_state_mkFSMstate.METH_read();
	 DEF_INST_top_DEF_abort_whas____d253 = INST_top.INST_abort.METH_whas();
	 DEF_INST_top_DEF_abort_wget____d254 = INST_top.INST_abort.METH_wget();
	 DEF_INST_top_DEF_f_rsps_i_notEmpty____d304 = INST_top.INST_f_rsps.METH_i_notEmpty();
	 DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277 = !DEF_INST_top_DEF_abort_whas____d253 || !DEF_INST_top_DEF_abort_wget____d254;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l100c11 = DEF_INST_top_DEF_f_rsps_i_notEmpty____d304 && (DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277 && DEF_INST_top_DEF_state_mkFSMstate_read____d281 == (tUInt8)13u);
	 INST_top.DEF_WILL_FIRE_RL_action_l100c11 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l100c11;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l101c11 = DEF_INST_top_DEF_f_rsps_i_notEmpty____d304 && (DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277 && DEF_INST_top_DEF_state_mkFSMstate_read____d281 == (tUInt8)14u);
	 INST_top.DEF_WILL_FIRE_RL_action_l101c11 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l101c11;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l102c11 = DEF_INST_top_DEF_f_rsps_i_notEmpty____d304 && (DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277 && DEF_INST_top_DEF_state_mkFSMstate_read____d281 == (tUInt8)15u);
	 INST_top.DEF_WILL_FIRE_RL_action_l102c11 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l102c11;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l103c11 = DEF_INST_top_DEF_f_rsps_i_notEmpty____d304 && (DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277 && DEF_INST_top_DEF_state_mkFSMstate_read____d281 == (tUInt8)16u);
	 INST_top.DEF_WILL_FIRE_RL_action_l103c11 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l103c11;
	 DEF_INST_top_DEF_f_reqs_i_notFull____d288 = INST_top.INST_f_reqs.METH_i_notFull();
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l104c11 = DEF_INST_top_DEF_f_reqs_i_notFull____d288 && (DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277 && DEF_INST_top_DEF_state_mkFSMstate_read____d281 == (tUInt8)17u);
	 INST_top.DEF_WILL_FIRE_RL_action_l104c11 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l104c11;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l105c11 = DEF_INST_top_DEF_f_reqs_i_notFull____d288 && (DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277 && DEF_INST_top_DEF_state_mkFSMstate_read____d281 == (tUInt8)18u);
	 INST_top.DEF_WILL_FIRE_RL_action_l105c11 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l105c11;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l106c11 = DEF_INST_top_DEF_f_reqs_i_notFull____d288 && (DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277 && DEF_INST_top_DEF_state_mkFSMstate_read____d281 == (tUInt8)19u);
	 INST_top.DEF_WILL_FIRE_RL_action_l106c11 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l106c11;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l107c11 = DEF_INST_top_DEF_f_reqs_i_notFull____d288 && (DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277 && DEF_INST_top_DEF_state_mkFSMstate_read____d281 == (tUInt8)20u);
	 INST_top.DEF_WILL_FIRE_RL_action_l107c11 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l107c11;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l108c11 = DEF_INST_top_DEF_f_rsps_i_notEmpty____d304 && (DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277 && DEF_INST_top_DEF_state_mkFSMstate_read____d281 == (tUInt8)21u);
	 INST_top.DEF_WILL_FIRE_RL_action_l108c11 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l108c11;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l109c11 = DEF_INST_top_DEF_f_rsps_i_notEmpty____d304 && (DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277 && DEF_INST_top_DEF_state_mkFSMstate_read____d281 == (tUInt8)22u);
	 INST_top.DEF_WILL_FIRE_RL_action_l109c11 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l109c11;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l111c11 = DEF_INST_top_DEF_f_rsps_i_notEmpty____d304 && (DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277 && DEF_INST_top_DEF_state_mkFSMstate_read____d281 == (tUInt8)24u);
	 INST_top.DEF_WILL_FIRE_RL_action_l111c11 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l111c11;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l110c11 = DEF_INST_top_DEF_f_rsps_i_notEmpty____d304 && (DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277 && DEF_INST_top_DEF_state_mkFSMstate_read____d281 == (tUInt8)23u);
	 INST_top.DEF_WILL_FIRE_RL_action_l110c11 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l110c11;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l112c11 = DEF_INST_top_DEF_f_reqs_i_notFull____d288 && (DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277 && DEF_INST_top_DEF_state_mkFSMstate_read____d281 == (tUInt8)25u);
	 INST_top.DEF_WILL_FIRE_RL_action_l112c11 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l112c11;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l113c11 = DEF_INST_top_DEF_f_reqs_i_notFull____d288 && (DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277 && DEF_INST_top_DEF_state_mkFSMstate_read____d281 == (tUInt8)26u);
	 INST_top.DEF_WILL_FIRE_RL_action_l113c11 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l113c11;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l114c11 = DEF_INST_top_DEF_f_rsps_i_notEmpty____d304 && (DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277 && DEF_INST_top_DEF_state_mkFSMstate_read____d281 == (tUInt8)27u);
	 INST_top.DEF_WILL_FIRE_RL_action_l114c11 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l114c11;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l115c11 = DEF_INST_top_DEF_f_rsps_i_notEmpty____d304 && (DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277 && DEF_INST_top_DEF_state_mkFSMstate_read____d281 == (tUInt8)28u);
	 INST_top.DEF_WILL_FIRE_RL_action_l115c11 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l115c11;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l88c11 = DEF_INST_top_DEF_f_reqs_i_notFull____d288 && (DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277 && DEF_INST_top_DEF_state_mkFSMstate_read____d281 == (tUInt8)1u);
	 INST_top.DEF_WILL_FIRE_RL_action_l88c11 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l88c11;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l89c11 = DEF_INST_top_DEF_f_reqs_i_notFull____d288 && (DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277 && DEF_INST_top_DEF_state_mkFSMstate_read____d281 == (tUInt8)2u);
	 INST_top.DEF_WILL_FIRE_RL_action_l89c11 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l89c11;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l90c11 = DEF_INST_top_DEF_f_reqs_i_notFull____d288 && (DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277 && DEF_INST_top_DEF_state_mkFSMstate_read____d281 == (tUInt8)3u);
	 INST_top.DEF_WILL_FIRE_RL_action_l90c11 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l90c11;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l92c11 = DEF_INST_top_DEF_f_rsps_i_notEmpty____d304 && (DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277 && DEF_INST_top_DEF_state_mkFSMstate_read____d281 == (tUInt8)5u);
	 INST_top.DEF_WILL_FIRE_RL_action_l92c11 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l92c11;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l91c11 = DEF_INST_top_DEF_f_reqs_i_notFull____d288 && (DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277 && DEF_INST_top_DEF_state_mkFSMstate_read____d281 == (tUInt8)4u);
	 INST_top.DEF_WILL_FIRE_RL_action_l91c11 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l91c11;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l93c11 = DEF_INST_top_DEF_f_rsps_i_notEmpty____d304 && (DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277 && DEF_INST_top_DEF_state_mkFSMstate_read____d281 == (tUInt8)6u);
	 INST_top.DEF_WILL_FIRE_RL_action_l93c11 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l93c11;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l94c11 = DEF_INST_top_DEF_f_rsps_i_notEmpty____d304 && (DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277 && DEF_INST_top_DEF_state_mkFSMstate_read____d281 == (tUInt8)7u);
	 INST_top.DEF_WILL_FIRE_RL_action_l94c11 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l94c11;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l96c11 = DEF_INST_top_DEF_f_reqs_i_notFull____d288 && (DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277 && DEF_INST_top_DEF_state_mkFSMstate_read____d281 == (tUInt8)9u);
	 INST_top.DEF_WILL_FIRE_RL_action_l96c11 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l96c11;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l95c11 = DEF_INST_top_DEF_f_rsps_i_notEmpty____d304 && (DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277 && DEF_INST_top_DEF_state_mkFSMstate_read____d281 == (tUInt8)8u);
	 INST_top.DEF_WILL_FIRE_RL_action_l95c11 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l95c11;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l97c11 = DEF_INST_top_DEF_f_reqs_i_notFull____d288 && (DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277 && DEF_INST_top_DEF_state_mkFSMstate_read____d281 == (tUInt8)10u);
	 INST_top.DEF_WILL_FIRE_RL_action_l97c11 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l97c11;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l98c11 = DEF_INST_top_DEF_f_reqs_i_notFull____d288 && (DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277 && DEF_INST_top_DEF_state_mkFSMstate_read____d281 == (tUInt8)11u);
	 INST_top.DEF_WILL_FIRE_RL_action_l98c11 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l98c11;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l99c11 = DEF_INST_top_DEF_f_reqs_i_notFull____d288 && (DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277 && DEF_INST_top_DEF_state_mkFSMstate_read____d281 == (tUInt8)12u);
	 INST_top.DEF_WILL_FIRE_RL_action_l99c11 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l99c11;
	 DEF_INST_top_DEF_state_fired__h50558 = INST_top.INST_state_fired.METH_read();
	 DEF_INST_top_DEF_start_reg_1__h50556 = INST_top.INST_start_reg_1.METH_read();
	 DEF_INST_top_DEF_running__h61733 = INST_top.INST_running.METH_read();
	 DEF_INST_top_DEF_start_reg__h61647 = INST_top.INST_start_reg.METH_read();
	 DEF_INST_top_DEF_state_mkFSMstate_read__81_EQ_29___d284 = DEF_INST_top_DEF_state_mkFSMstate_read____d281 == (tUInt8)29u;
	 DEF_INST_top_DEF_abort_whas__53_AND_abort_wget__54___d255 = DEF_INST_top_DEF_abort_whas____d253 && DEF_INST_top_DEF_abort_wget____d254;
	 DEF_INST_top_DEF_abort_whas__53_AND_abort_wget__54_55_OR_state__ETC___d285 = (DEF_INST_top_DEF_abort_whas__53_AND_abort_wget__54___d255 || DEF_INST_top_DEF_state_mkFSMstate_read____d281 == (tUInt8)0u) || DEF_INST_top_DEF_state_mkFSMstate_read__81_EQ_29___d284;
	 DEF_INST_top_DEF_abort_whas__53_AND_abort_wget__54_55_OR_state__ETC___d458 = DEF_INST_top_DEF_abort_whas__53_AND_abort_wget__54_55_OR_state__ETC___d285 && (!DEF_INST_top_DEF_start_reg_1__h50556 || DEF_INST_top_DEF_state_fired__h50558);
	 DEF_INST_top_DEF_abort_whas__53_AND_abort_wget__54_55_OR_state__ETC___d462 = DEF_INST_top_DEF_abort_whas__53_AND_abort_wget__54_55_OR_state__ETC___d458 && !DEF_INST_top_DEF_start_reg__h61647;
	 DEF_INST_top_DEF_CAN_FIRE_RL_auto_finish = DEF_INST_top_DEF_running__h61733 && DEF_INST_top_DEF_abort_whas__53_AND_abort_wget__54_55_OR_state__ETC___d462;
	 DEF_INST_top_DEF_WILL_FIRE_RL_auto_finish = DEF_INST_top_DEF_CAN_FIRE_RL_auto_finish;
	 DEF_INST_top_DEF_CAN_FIRE_RL_auto_start = DEF_INST_top_DEF_abort_whas__53_AND_abort_wget__54_55_OR_state__ETC___d462 && !DEF_INST_top_DEF_running__h61733;
	 DEF_INST_top_DEF_WILL_FIRE_RL_auto_start = DEF_INST_top_DEF_CAN_FIRE_RL_auto_start;
	 DEF_INST_top_DEF_CAN_FIRE_RL_fsm_start = DEF_INST_top_DEF_abort_whas__53_AND_abort_wget__54_55_OR_state__ETC___d458 && DEF_INST_top_DEF_start_reg__h61647;
	 DEF_INST_top_DEF_WILL_FIRE_RL_fsm_start = DEF_INST_top_DEF_CAN_FIRE_RL_fsm_start;
	 DEF_INST_top_DEF_mems_devices_rg_running___d15 = INST_top.INST_mems_devices_rg_running.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_mems_devices_rl_Dbg_req_rsp = (INST_top.INST_f_reqs.METH_i_notEmpty() && INST_top.INST_f_rsps.METH_i_notFull()) && DEF_INST_top_DEF_mems_devices_rg_running___d15;
	 DEF_INST_top_DEF_WILL_FIRE_RL_mems_devices_rl_Dbg_req_rsp = DEF_INST_top_DEF_CAN_FIRE_RL_mems_devices_rl_Dbg_req_rsp;
	 DEF_INST_top_DEF_CAN_FIRE_RL_mems_devices_rl_count_MTIME = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_mems_devices_rl_count_MTIME = DEF_INST_top_DEF_CAN_FIRE_RL_mems_devices_rl_count_MTIME;
	 INST_top.DEF_mems_devices_spec_sto_buf_f_rsp_from_mem_rv_po_ETC___d1 = INST_top.INST_mems_devices_spec_sto_buf_f_rsp_from_mem_rv.METH_port0__read();
	 DEF_INST_top_DEF_x__h2881 = INST_top.DEF_mems_devices_spec_sto_buf_f_rsp_from_mem_rv_po_ETC___d1.get_bits_in_word8(6u,
															    2u,
															    5u);
	 DEF_INST_top_DEF_CAN_FIRE_RL_mems_devices_spec_sto_buf_rl_mem_wr_rsp = INST_top.DEF_mems_devices_spec_sto_buf_f_rsp_from_mem_rv_po_ETC___d1.get_bits_in_word8(8u,
																				       9u,
																				       1u) && DEF_INST_top_DEF_x__h2881 == (tUInt8)31u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_mems_devices_spec_sto_buf_rl_mem_wr_rsp = DEF_INST_top_DEF_CAN_FIRE_RL_mems_devices_spec_sto_buf_rl_mem_wr_rsp;
	 DEF_INST_top_DEF_CAN_FIRE_RL_restart = (DEF_INST_top_DEF_start_reg_1__h50556 && !DEF_INST_top_DEF_state_fired__h50558) && DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277;
	 DEF_INST_top_DEF_WILL_FIRE_RL_restart = DEF_INST_top_DEF_CAN_FIRE_RL_restart;
	 DEF_INST_top_DEF_CAN_FIRE_RL_state_fired__dreg_update = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_state_fired__dreg_update = DEF_INST_top_DEF_CAN_FIRE_RL_state_fired__dreg_update;
	 DEF_INST_top_DEF_CAN_FIRE_RL_start_reg__dreg_update = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_start_reg__dreg_update = DEF_INST_top_DEF_CAN_FIRE_RL_start_reg__dreg_update;
	 DEF_INST_top_DEF_CAN_FIRE_RL_state_every = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_state_every = DEF_INST_top_DEF_CAN_FIRE_RL_state_every;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_10 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_10 = DEF_INST_top_DEF_CAN_FIRE___me_check_10;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_11 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_11 = DEF_INST_top_DEF_CAN_FIRE___me_check_11;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_12 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_12 = DEF_INST_top_DEF_CAN_FIRE___me_check_12;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_13 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_13 = DEF_INST_top_DEF_CAN_FIRE___me_check_13;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_14 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_14 = DEF_INST_top_DEF_CAN_FIRE___me_check_14;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_17 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_17 = DEF_INST_top_DEF_CAN_FIRE___me_check_17;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_15 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_15 = DEF_INST_top_DEF_CAN_FIRE___me_check_15;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_16 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_16 = DEF_INST_top_DEF_CAN_FIRE___me_check_16;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_18 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_18 = DEF_INST_top_DEF_CAN_FIRE___me_check_18;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_19 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_19 = DEF_INST_top_DEF_CAN_FIRE___me_check_19;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_20 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_20 = DEF_INST_top_DEF_CAN_FIRE___me_check_20;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_21 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_21 = DEF_INST_top_DEF_CAN_FIRE___me_check_21;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_22 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_22 = DEF_INST_top_DEF_CAN_FIRE___me_check_22;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_23 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_23 = DEF_INST_top_DEF_CAN_FIRE___me_check_23;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_24 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_24 = DEF_INST_top_DEF_CAN_FIRE___me_check_24;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_25 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_25 = DEF_INST_top_DEF_CAN_FIRE___me_check_25;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_26 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_26 = DEF_INST_top_DEF_CAN_FIRE___me_check_26;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_27 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_27 = DEF_INST_top_DEF_CAN_FIRE___me_check_27;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_28 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_28 = DEF_INST_top_DEF_CAN_FIRE___me_check_28;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_29 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_29 = DEF_INST_top_DEF_CAN_FIRE___me_check_29;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_30 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_30 = DEF_INST_top_DEF_CAN_FIRE___me_check_30;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_31 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_31 = DEF_INST_top_DEF_CAN_FIRE___me_check_31;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_34 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_34 = DEF_INST_top_DEF_CAN_FIRE___me_check_34;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_32 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_32 = DEF_INST_top_DEF_CAN_FIRE___me_check_32;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_33 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_33 = DEF_INST_top_DEF_CAN_FIRE___me_check_33;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_35 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_35 = DEF_INST_top_DEF_CAN_FIRE___me_check_35;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_36 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_36 = DEF_INST_top_DEF_CAN_FIRE___me_check_36;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_9 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_9 = DEF_INST_top_DEF_CAN_FIRE___me_check_9;
	 if (INST_top.DEF_WILL_FIRE_RL_action_l100c11)
	   INST_top.RL_action_l100c11();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l101c11)
	   INST_top.RL_action_l101c11();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l102c11)
	   INST_top.RL_action_l102c11();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l103c11)
	   INST_top.RL_action_l103c11();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l104c11)
	   INST_top.RL_action_l104c11();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l105c11)
	   INST_top.RL_action_l105c11();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l106c11)
	   INST_top.RL_action_l106c11();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l107c11)
	   INST_top.RL_action_l107c11();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l108c11)
	   INST_top.RL_action_l108c11();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l109c11)
	   INST_top.RL_action_l109c11();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l110c11)
	   INST_top.RL_action_l110c11();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l111c11)
	   INST_top.RL_action_l111c11();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l114c11)
	   INST_top.RL_action_l114c11();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l112c11)
	   INST_top.RL_action_l112c11();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l113c11)
	   INST_top.RL_action_l113c11();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l115c11)
	   INST_top.RL_action_l115c11();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l88c11)
	   INST_top.RL_action_l88c11();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l89c11)
	   INST_top.RL_action_l89c11();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l90c11)
	   INST_top.RL_action_l90c11();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l91c11)
	   INST_top.RL_action_l91c11();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l92c11)
	   INST_top.RL_action_l92c11();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l93c11)
	   INST_top.RL_action_l93c11();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l94c11)
	   INST_top.RL_action_l94c11();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l95c11)
	   INST_top.RL_action_l95c11();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l96c11)
	   INST_top.RL_action_l96c11();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l97c11)
	   INST_top.RL_action_l97c11();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l98c11)
	   INST_top.RL_action_l98c11();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l99c11)
	   INST_top.RL_action_l99c11();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_auto_start)
	   INST_top.RL_auto_start();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_mems_devices_rl_count_MTIME)
	   INST_top.RL_mems_devices_rl_count_MTIME();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_mems_devices_spec_sto_buf_rl_mem_wr_rsp)
	   INST_top.RL_mems_devices_spec_sto_buf_rl_mem_wr_rsp();
	 INST_top.DEF_mems_devices_spec_sto_buf_f_rsp_from_mem_rv_po_ETC___d11 = INST_top.INST_mems_devices_spec_sto_buf_f_rsp_from_mem_rv.METH_port1__read();
	 INST_top.DEF_mems_devices_spec_sto_buf_f_req_to_mem_rv_port_ETC___d9 = INST_top.INST_mems_devices_spec_sto_buf_f_req_to_mem_rv.METH_port1__read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_mems_devices_rl_DMem_req_rsp = (INST_top.DEF_mems_devices_spec_sto_buf_f_req_to_mem_rv_port_ETC___d9.get_bits_in_word8(8u,
																			     7u,
																			     1u) && !INST_top.DEF_mems_devices_spec_sto_buf_f_rsp_from_mem_rv_po_ETC___d11.get_bits_in_word8(8u,
																															     9u,
																															     1u)) && DEF_INST_top_DEF_mems_devices_rg_running___d15;
	 DEF_INST_top_DEF_WILL_FIRE_RL_mems_devices_rl_DMem_req_rsp = DEF_INST_top_DEF_CAN_FIRE_RL_mems_devices_rl_DMem_req_rsp;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_restart)
	   INST_top.RL_restart();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_10)
	   INST_top.__me_check_10();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_11)
	   INST_top.__me_check_11();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_12)
	   INST_top.__me_check_12();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_13)
	   INST_top.__me_check_13();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_14)
	   INST_top.__me_check_14();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_15)
	   INST_top.__me_check_15();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_17)
	   INST_top.__me_check_17();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_16)
	   INST_top.__me_check_16();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_18)
	   INST_top.__me_check_18();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_20)
	   INST_top.__me_check_20();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_19)
	   INST_top.__me_check_19();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_21)
	   INST_top.__me_check_21();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_22)
	   INST_top.__me_check_22();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_23)
	   INST_top.__me_check_23();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_25)
	   INST_top.__me_check_25();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_24)
	   INST_top.__me_check_24();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_26)
	   INST_top.__me_check_26();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_27)
	   INST_top.__me_check_27();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_29)
	   INST_top.__me_check_29();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_28)
	   INST_top.__me_check_28();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_30)
	   INST_top.__me_check_30();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_31)
	   INST_top.__me_check_31();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_32)
	   INST_top.__me_check_32();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_33)
	   INST_top.__me_check_33();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_34)
	   INST_top.__me_check_34();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_35)
	   INST_top.__me_check_35();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_36)
	   INST_top.__me_check_36();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_fsm_start)
	   INST_top.RL_fsm_start();
	 DEF_INST_top_DEF_start_wire_whas____d256 = INST_top.INST_start_wire.METH_whas();
	 DEF_INST_top_DEF_start_wire_wget____d258 = INST_top.INST_start_wire.METH_wget();
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l82c10 = (!DEF_INST_top_DEF_mems_devices_rg_running___d15 && ((DEF_INST_top_DEF_start_wire_whas____d256 && DEF_INST_top_DEF_start_wire_wget____d258) && DEF_INST_top_DEF_abort_whas__53_AND_abort_wget__54_55_OR_state__ETC___d285)) && !(((((DEF_INST_top_DEF_CAN_FIRE_RL_action_l115c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l114c11) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l113c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l112c11)) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_l111c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l110c11) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l109c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l108c11))) || (((DEF_INST_top_DEF_CAN_FIRE_RL_action_l107c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l106c11) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l105c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l104c11)) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_l103c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l102c11) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l101c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l100c11)))) || ((((DEF_INST_top_DEF_CAN_FIRE_RL_action_l99c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l98c11) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l97c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l96c11)) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_l95c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l94c11) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l93c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l92c11))) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_l91c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l90c11) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l89c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l88c11))));
	 INST_top.DEF_WILL_FIRE_RL_action_l82c10 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l82c10;
	 DEF_INST_top_DEF_NOT_start_wire_whas__56_57_OR_NOT_start_wire_w_ETC___d260 = !DEF_INST_top_DEF_start_wire_whas____d256 || !DEF_INST_top_DEF_start_wire_wget____d258;
	 DEF_INST_top_DEF_CAN_FIRE_RL_idle_l81c7 = (DEF_INST_top_DEF_NOT_start_wire_whas__56_57_OR_NOT_start_wire_w_ETC___d260 && (DEF_INST_top_DEF_NOT_abort_whas__53_75_OR_NOT_abort_wget__54_76___d277 && DEF_INST_top_DEF_state_mkFSMstate_read__81_EQ_29___d284)) && !(((((DEF_INST_top_DEF_CAN_FIRE_RL_action_l115c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l114c11) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l113c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l112c11)) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_l111c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l110c11) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l109c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l108c11))) || (((DEF_INST_top_DEF_CAN_FIRE_RL_action_l107c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l106c11) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l105c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l104c11)) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_l103c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l102c11) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l101c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l100c11)))) || ((((DEF_INST_top_DEF_CAN_FIRE_RL_action_l99c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l98c11) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l97c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l96c11)) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_l95c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l94c11) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l93c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l92c11))) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_l91c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l90c11) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l89c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l88c11))));
	 DEF_INST_top_DEF_WILL_FIRE_RL_idle_l81c7 = DEF_INST_top_DEF_CAN_FIRE_RL_idle_l81c7;
	 DEF_INST_top_DEF_CAN_FIRE_RL_state_handle_abort = (DEF_INST_top_DEF_abort_whas__53_AND_abort_wget__54___d255 && DEF_INST_top_DEF_NOT_start_wire_whas__56_57_OR_NOT_start_wire_w_ETC___d260) && !(((((DEF_INST_top_DEF_CAN_FIRE_RL_action_l115c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l114c11) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l113c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l112c11)) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_l111c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l110c11) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l109c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l108c11))) || (((DEF_INST_top_DEF_CAN_FIRE_RL_action_l107c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l106c11) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l105c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l104c11)) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_l103c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l102c11) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l101c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l100c11)))) || ((((DEF_INST_top_DEF_CAN_FIRE_RL_action_l99c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l98c11) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l97c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l96c11)) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_l95c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l94c11) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l93c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l92c11))) || (((DEF_INST_top_DEF_CAN_FIRE_RL_action_l91c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l90c11) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l89c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l88c11)) || DEF_INST_top_DEF_CAN_FIRE_RL_restart)));
	 DEF_INST_top_DEF_WILL_FIRE_RL_state_handle_abort = DEF_INST_top_DEF_CAN_FIRE_RL_state_handle_abort;
	 if (INST_top.DEF_WILL_FIRE_RL_action_l82c10)
	   INST_top.RL_action_l82c10();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_auto_finish)
	   INST_top.RL_auto_finish();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_mems_devices_rl_Dbg_req_rsp)
	   INST_top.RL_mems_devices_rl_Dbg_req_rsp();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_mems_devices_rl_DMem_req_rsp)
	   INST_top.RL_mems_devices_rl_DMem_req_rsp();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_start_reg__dreg_update)
	   INST_top.RL_start_reg__dreg_update();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_state_handle_abort)
	   INST_top.RL_state_handle_abort();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_9)
	   INST_top.__me_check_9();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_idle_l81c7)
	   INST_top.RL_idle_l81c7();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_state_every)
	   INST_top.RL_state_every();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_state_fired__dreg_update)
	   INST_top.RL_state_fired__dreg_update();
	 INST_top.INST_state_fired_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_state_overlap_pw.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_state_set_pw.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_abort.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_start_reg_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_start_wire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_mems_devices_spec_sto_buf_f_rsp_from_mem_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_mems_devices_spec_sto_buf_f_req_to_mem_rv.clk((tUInt8)1u, (tUInt8)1u);
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_f_reqs.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_f_rsps.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_mems_devices_spec_sto_buf_rg_logfile.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mems_devices_spec_sto_buf_f_req_to_mem_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_mems_devices_spec_sto_buf_f_rsp_from_mem_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_mems_devices_spec_sto_buf_rg_free_ix.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mems_devices_spec_sto_buf_rg_fsm_state.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mems_devices_rg_running.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mems_devices_rg_logfile.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mems_devices_rg_MTIME.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_start_reg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_start_reg_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_state_mkFSMstate.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_state_fired.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_state_can_overlap.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_running.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkTop::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkTop_instance = new MOD_mkTop(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkTop_instance->INST_f_reqs.set_clk_0)("CLK");
  (mkTop_instance->INST_f_rsps.set_clk_0)("CLK");
  (mkTop_instance->INST_mems_devices_spec_sto_buf_f_req_to_mem_rv.set_clk_0)("CLK");
  (mkTop_instance->INST_mems_devices_spec_sto_buf_f_rsp_from_mem_rv.set_clk_0)("CLK");
  (mkTop_instance->INST_start_wire.set_clk_0)("CLK");
  (mkTop_instance->INST_start_reg_2.set_clk_0)("CLK");
  (mkTop_instance->INST_abort.set_clk_0)("CLK");
  (mkTop_instance->INST_state_set_pw.set_clk_0)("CLK");
  (mkTop_instance->INST_state_overlap_pw.set_clk_0)("CLK");
  (mkTop_instance->INST_state_fired_1.set_clk_0)("CLK");
  (mkTop_instance->set_clk_0)("CLK");
}
void MODEL_mkTop::destroy_model()
{
  delete mkTop_instance;
  mkTop_instance = NULL;
}
void MODEL_mkTop::reset_model(bool asserted)
{
  (mkTop_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkTop::get_instance()
{
  return mkTop_instance;
}

/* Fill in version numbers */
void MODEL_mkTop::get_version(char const **name, char const **build)
{
  *name = "2024.07";
  *build = "b4f31db";
}

/* Get the model creation time */
time_t MODEL_mkTop::get_creation_time()
{
  
  /* Fri Jan  3 21:31:10 UTC 2025 */
  return 1735939870llu;
}

/* State dumping function */
void MODEL_mkTop::dump_state()
{
  (mkTop_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkTop & mkTop_backing(tSimStateHdl simHdl)
{
  static MOD_mkTop *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkTop(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkTop::dump_VCD_defs()
{
  (mkTop_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkTop::dump_VCD(tVCDDumpType dt)
{
  (mkTop_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkTop_backing(sim_hdl));
}
